#!/bin/bash

# Define an array of file names
files=(
    0-body_size.sh
    1-body.sh
    2-delete.sh
    3-methods.sh
    4-header.sh
    5-post_params.sh
    100-status_code.sh
    101-post_json.sh
    102-catch_me.sh
)

# Loop through the array and create files
for file in "${files[@]}"; do
    touch "$file"  # Create file
    chmod +x "$file"  # Make file executable
    echo "#!/bin/bash" > "$file"  # Write shebang to file
done
