#!/usr/bin/python3

names=(
    0-safe_print_list.py
    1-safe_print_integer.py
    2-safe_print_list_integers.py
    3-safe_print_division.py
    4-list_division.py
    5-raise_exception.py
    6-raise_exception_msg.py
    100-safe_print_integer_err.py
    101-safe_function.py
    102-magic_calculation.py
)

for name in "${names[@]}"; do
    # Create the file
    touch "$name"
    # Add execute permission
    chmod +x "$name"
    # Add shebang line to the file
    echo "#!/bin/python3" > "$name"
done
