#!/bin/bash

# Define the tuple of names
names=(
"0-square_matrix_simple.py"
"1-search_replace.py"
"2-uniq_add.py"
"3-common_elements.py"
"4-only_diff_elements.py"
"5-number_keys.py"
"6-print_sorted_dictionary.py"
"7-update_dictionary.py"
"8-simple_delete.py"
"9-multiply_by_2.py"
"10-best_score.py"
"11-multiply_list_map.py"
"12-roman_to_int.py"
"100-weight_average.py"
"101-square_matrix_map.py"
"102-complex_delete.py"
)

# Iterate over each name in the tuple
for name in "${names[@]}"; do
    # Create a new file with the name
    touch "$name"
    # Make the file executable
    chmod +x "$name"
    # Add the shebang line at the beginning of the file
    echo "#!/usr/bin/python3" > "$name"
done
