#!/usr/bin/bash

# Define an array of file names
names=(
    "0-positive_or_negative.py"
    "1-last_digit.py"
    "2-print_alphabet.py"
    "3-print_alphabt.py"
    "4-print_hexa.py"
    "5-print_comb2.py"
    "6-print_comb3.py"
    "7-islower.py"
    "7-islower.py"
    "8-uppercase.py"
    "9-print_last_digit.py"
    "10-add.py"
    "11-pow.py"
    "12-fizzbuzz.py"
    "100-print_tebahpla.py"
    "101-remove_char_at.py"
    "102-magic_calculation.py"
)

# Loop through each name in the array
for name in "${names[@]}"; do
    # Create a new file with the given name
    touch "$name"
    # Add execute permissions to the file
    chmod +x "$name"
    # Write the shebang line to the file
    echo '#!/usr/bin/python3' > "$name"
done

